"""内置预设 LLM 供应商目录 (2026-07-12 从 llm_manager 抽出)。

包含两份纯静态数据:
  - ENV_PREFIX_MAP: provider_id -> 环境变量名 (读 API Key)
  - BUILTIN_CONFIGS: 预设供应商列表, 与前端 TEMPLATE_OPTIONS 对齐

抽出前这两坨数据约 780 行, 塞在 LLMManager._load_builtin_providers 方法体里,
使该文件极度臃肿。抽出后 llm_manager 只保留"合并 env / config override"的行为逻辑。

⚠️  这里只放不依赖运行时状态的静态目录数据; 任何读环境变量 /
    config.toml / 磁盘的动态逻辑都留在 llm_manager。
"""
from typing import Any, Dict, List

ENV_PREFIX_MAP: Dict[str, str] = {
    'openai': 'OPENAI_API_KEY',
    'edgefn': 'EDGEFN_API_KEY',
    'sheng_suan_yun': 'SHENG_SUAN_YUN_API_KEY',
    'patewayai': 'PATEWAYAI_API_KEY',
    'volcengine_agentplan': 'VOLCENGINE_AGENTPLAN_API_KEY',
    'byteplus': 'BYTEPLUS_API_KEY',
    'doubaoseed': 'DOUBAOSEED_API_KEY',
    'ccsub': 'CCSUB_API_KEY',
    'unity2ai': 'UNITY2AI_API_KEY',
    'siliconflow': 'SILICONFLOW_API_KEY',
    'siliconflow_en': 'SILICONFLOW_EN_API_KEY',
    'dmxapi': 'DMXAPI_API_KEY',
    'packycode': 'PACKYCODE_API_KEY',
    'apikey_fun': 'APIKEY_FUN_API_KEY',
    'apinebula': 'APINEBULA_API_KEY',
    'atlascloud': 'ATLASCLOUD_API_KEY',
    'sudocode': 'SUDOCODE_API_KEY',
    'claude_cn': 'CLAUDE_CN_API_KEY',
    'runapi': 'RUNAPI_API_KEY',
    'relaxycode': 'RELAXYCODE_API_KEY',
    'cubence': 'CUBENCE_API_KEY',
    'aigocode': 'AIGOCODE_API_KEY',
    'rightcode': 'RIGHTCODE_API_KEY',
    'aicodemirror': 'AICODEMIRROR_API_KEY',
    'crazyrouter': 'CRAZYROUTER_API_KEY',
    'sssaicode': 'SSSAICODE_API_KEY',
    'youyun': 'YOUYUN_API_KEY',
    'youyun_coding': 'YOUYUN_CODING_API_KEY',
    'micu': 'MICU_API_KEY',
    'ctok': 'CTOK_API_KEY',
    'azure_openai': 'AZURE_OPENAI_API_KEY',
    'deepseek': 'DEEPSEEK_API_KEY',
    'zhipu': 'ZHIPU_API_KEY',
    'zhipu_en': 'ZHIPU_EN_API_KEY',
    'qianfan': 'QIANFAN_API_KEY',
    'bailian': 'BAILIAN_API_KEY',
    'kimi': 'KIMI_API_KEY',
    'kimi_coding': 'KIMI_CODING_API_KEY',
    'stepfun': 'STEPFUN_API_KEY',
    'stepfun_en': 'STEPFUN_EN_API_KEY',
    'modelscope': 'MODELSCOPE_API_KEY',
    'longcat': 'LONGCAT_API_KEY',
    'minimax': 'MINIMAX_API_KEY',
    'minimax_en': 'MINIMAX_EN_API_KEY',
    'bailing': 'BAILING_API_KEY',
    'xiaomi_mimo': 'XIAOMI_MIMO_API_KEY',
    'xiaomi_mimo_turbo': 'XIAOMI_MIMO_TURBO_API_KEY',
    'novita_ai': 'NOVITA_AI_API_KEY',
    'nvidia': 'NVIDIA_API_KEY',
    'aihubmix': 'AIHUBMIX_API_KEY',
    'cherryin': 'CHERRYIN_API_KEY',
    'eflowcode': 'EFLOWCODE_API_KEY',
    'pipellm': 'PIPELLM_API_KEY',
    'openrouter': 'OPENROUTER_API_KEY',
    'therouter': 'THEROUTER_API_KEY',
}
# 内置供应商配置，和前端完全一致
BUILTIN_CONFIGS: List[Dict[str, Any]] = [
    # 星标推荐
    {
        'id': 'edgefn',
        'name': '⚡ EdgeFn聚合',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.edgefn.net/v1',
        'default_model': 'GLM-4.5V',  # W5-2: 部署默认 GLM-4.5V (跟 config.py / HARDCODED_API_KEY 对齐)
        'models': ['GLM-4.5V', 'GLM-5.2', 'GLM-4-flash', 'deepseek-v4-flash', 'deepseek-v4-pro', 'deepseek-chat'],
        'icon': '⚡',
        'color': '#F59E0B',
        'notes': 'EdgeFn聚合代理，一个Key支持智谱/DeepSeek等多模型，国内访问稳定',
        'star': True,
    },
    {
        'id': 'openai',
        'name': '🟢 OpenAI Official',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.openai.com/v1',
        'default_model': 'gpt-4o',
        'models': ['gpt-4o', 'gpt-4o-mini', 'gpt-5', 'o3-mini'],
        'icon': '🟢',
        'color': '#10A37F',
        'notes': '官方接口地址正确，请填写你已开通权限的模型ID',
        'star': True,
    },
    {
        'id': 'sheng_suan_yun',
        'name': '🟣 胜算云',
        'protocol': 'openai_compatible',
        'base_url': 'https://router.shengsuanyun.com/api/v1',
        'default_model': 'claude-sonnet-4-6',
        'models': ['sheng-suan-7b'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': '胜算云模型接口。',
        'star': True,
    },
    {
        'id': 'patewayai',
        'name': '⚫ PatewayAI',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.patewayai.com/v1',
        'default_model': 'pateway-v1',
        'models': ['pateway-v1'],
        'icon': '⚫',
        'color': '#1f2937',
        'notes': 'PatewayAI官方接口。',
        'star': True,
    },
    {
        'id': 'volcengine_agentplan',
        'name': '🔵 火山Agentplan',
        'protocol': 'openai_compatible',
        'base_url': 'https://ark.cn-beijing.volces.com/api/v3',
        'default_model': 'doubao-seed-2-0-code-preview-latest',
        'models': ['doubao-pro-32k'],
        'icon': '🔵',
        'color': '#3b82f6',
        'notes': '火山引擎AgentPlan/豆包兼容接口。',
        'star': True,
    },
    {
        'id': 'byteplus',
        'name': '🔵 BytePlus',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.byteplus.com/v1',
        'default_model': 'byteplus-v1',
        'models': ['byteplus-v1'],
        'icon': '🔵',
        'color': '#3b82f6',
        'notes': 'BytePlus官方接口。',
        'star': True,
    },
    {
        'id': 'doubaoseed',
        'name': '🟣 DouBaoSeed',
        'protocol': 'openai_compatible',
        'base_url': 'https://ark.cn-beijing.volces.com/api/v3',
        'default_model': 'doubao-seed-2-0-code-preview-latest',
        'models': ['doubao-seed-128k'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': '字节跳动豆包Seed系列模型。',
        'star': True,
    },
    {
        'id': 'ccsub',
        'name': '🟢 CCSub',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.ccsub.com/v1',
        'default_model': 'ccsub-7b',
        'models': ['ccsub-7b'],
        'icon': '🟢',
        'color': '#22c55e',
        'notes': 'CCSub模型接口。',
        'star': True,
    },
    {
        'id': 'unity2ai',
        'name': '⚫ Unity2.ai',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.unity2.ai/v1',
        'default_model': 'unity-v1',
        'models': ['unity-v1'],
        'icon': '⚫',
        'color': '#1f2937',
        'notes': 'Unity2.ai官方接口。',
        'star': True,
    },
    {
        'id': 'siliconflow',
        'name': '💜 SiliconFlow',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.siliconflow.cn/v1',
        'default_model': 'deepseek-ai/DeepSeek-V3',
        'models': ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct', 'THUDM/glm-4-9b-chat'],
        'icon': '💜',
        'color': '#8b5cf6',
        'notes': '官方接口地址正确，请填写你已开通权限的模型ID',
        'star': True,
    },
    {
        'id': 'siliconflow_en',
        'name': '💜 SiliconFlow en',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.siliconflow.com/v1',
        'default_model': 'deepseek-v3',
        'models': ['deepseek-v3'],
        'icon': '💜',
        'color': '#8b5cf6',
        'notes': '硅基流动国际版接口。',
        'star': True,
    },
    {
        'id': 'dmxapi',
        'name': '⚪ DMXAPI',
        'protocol': 'openai_compatible',
        'base_url': 'https://www.dmxapi.cn/v1',
        'default_model': 'dmx-v1',
        'models': ['dmx-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': 'DMXAPI模型接口。',
        'star': True,
    },
    {
        'id': 'packycode',
        'name': '⚫ PackyCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://www.packyapi.com/v1',
        'default_model': 'packy-coder-v1',
        'models': ['packy-coder-v1'],
        'icon': '⚫',
        'color': '#1f2937',
        'notes': 'PackyCode代码大模型接口。',
        'star': True,
    },
    {
        'id': 'apikey_fun',
        'name': '🟠 APIKEY.FUN',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.apikey.fun/v1',
        'default_model': 'apikeyfun-v1',
        'models': ['apikeyfun-v1'],
        'icon': '🟠',
        'color': '#f59e0b',
        'notes': 'APIKEY.FUN聚合模型接口。',
        'star': True,
    },
    {
        'id': 'apinebula',
        'name': '⚪ APINebula',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.apinebula.com/v1',
        'default_model': 'apinebula-v1',
        'models': ['apinebula-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': 'APINebula星云模型接口。',
        'star': True,
    },
    {
        'id': 'atlascloud',
        'name': '▲ AtlasCloud',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.atlascloud.ai/v1',
        'default_model': 'atlas-v1',
        'models': ['atlas-v1'],
        'icon': '▲',
        'color': '#6366f1',
        'notes': 'AtlasCloud大模型接口。',
        'star': True,
    },
    {
        'id': 'sudocode',
        'name': '🟣 SudoCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.sudocode.com/v1',
        'default_model': 'sudo-coder-v1',
        'models': ['sudo-coder-v1'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': 'SudoCode代码大模型接口。',
        'star': True,
    },
    {
        'id': 'claude_cn',
        'name': '🍀 ClaudeCN',
        'protocol': 'openai_compatible',
        'base_url': 'https://claude.volcengineapi.com/v1',
        'default_model': 'claude-3-5-sonnet',
        'models': ['claude-3-5-sonnet'],
        'icon': '🍀',
        'color': '#4ade80',
        'notes': '火山方舟Claude国内节点接口。',
        'star': True,
    },
    {
        'id': 'runapi',
        'name': '⬛ RunAPI',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.runapi.com/v1',
        'default_model': 'runapi-v1',
        'models': ['runapi-v1'],
        'icon': '⬛',
        'color': '#18181b',
        'notes': 'RunAPI聚合模型接口。',
        'star': True,
    },
    {
        'id': 'relaxycode',
        'name': '⚪ RelaxyCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.relaxycode.com/v1',
        'default_model': 'relaxy-coder-v1',
        'models': ['relaxy-coder-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': 'RelaxyCode代码模型接口。',
        'star': True,
    },
    {
        'id': 'cubence',
        'name': '⬛ Cubence',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.cubence.com/v1',
        'default_model': 'cubence-v1',
        'models': ['cubence-v1'],
        'icon': '⬛',
        'color': '#18181b',
        'notes': 'Cubence模型接口。',
        'star': True,
    },
    {
        'id': 'aigocode',
        'name': '🟣 AIGoCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.aigocode.com',
        'default_model': 'aigo-coder-v1',
        'models': ['aigo-coder-v1'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': 'AIGoCode代码大模型接口。',
        'star': True,
    },
    {
        'id': 'rightcode',
        'name': '🟠 RightCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://right.codes/codex/v1',
        'default_model': 'right-coder-v1',
        'models': ['right-coder-v1'],
        'icon': '🟠',
        'color': '#f59e0b',
        'notes': 'RightCode代码模型接口。',
        'star': True,
    },
    {
        'id': 'aicodemirror',
        'name': '✖️ AICodeMirror',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.aicodemirror.com/api/codex/backend-api/codex',
        'default_model': 'aicm-v1',
        'models': ['aicm-v1'],
        'icon': '✖️',
        'color': '#ef4444',
        'notes': 'AICodeMirror镜像模型接口。',
        'star': True,
    },
    {
        'id': 'crazyrouter',
        'name': '⚪ CrazyRouter',
        'protocol': 'openai_compatible',
        'base_url': 'https://crazyrouter.com/v1',
        'default_model': 'crazy-v1',
        'models': ['crazy-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': 'CrazyRouter大模型路由接口。',
        'star': True,
    },
    {
        'id': 'sssaicode',
        'name': '⬛ SSSAiCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://node-hk.sssaicode.com/api/v1',
        'default_model': 'sssaicode-v1',
        'models': ['sssaicode-v1'],
        'icon': '⬛',
        'color': '#18181b',
        'notes': 'SSSAiCode代码模型接口。',
        'star': True,
    },
    {
        'id': 'youyun',
        'name': '🟣 优云智算',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.youyunzhisuan.com/v1',
        'default_model': 'youyun-v1',
        'models': ['youyun-v1'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': '优云智算大模型接口。',
        'star': True,
    },
    {
        'id': 'youyun_coding',
        'name': '🟣 优云智算Coding',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.youyunzhisuan.com/v1',
        'default_model': 'youyun-coder-v1',
        'models': ['youyun-coder-v1'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': '优云智算代码模型接口。',
        'star': True,
    },
    {
        'id': 'micu',
        'name': '🔵 Micu',
        'protocol': 'openai_compatible',
        'base_url': 'https://www.openclaudecode.cn/v1',
        'default_model': 'micu-v1',
        'models': ['micu-v1'],
        'icon': '🔵',
        'color': '#3b82f6',
        'notes': 'Micu大模型接口。',
        'star': True,
    },
    {
        'id': 'ctok',
        'name': '🔵 CTok.ai',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.ctok.ai/v1',
        'default_model': 'ctok-v1',
        'models': ['ctok-v1'],
        'icon': '🔵',
        'color': '#3b82f6',
        'notes': 'CTok.ai模型接口。',
        'star': True,
    },
    # 普通源
    {
        'id': 'azure_openai',
        'name': '🔵 Azure OpenAI',
        'protocol': 'openai_compatible',
        'base_url': 'https://{resource}.openai.azure.com/openai/deployments/{deployment}/v1',
        'default_model': 'gpt-4o',
        'models': ['gpt-4o'],
        'icon': '🔵',
        'color': '#3b82f6',
        'notes': '微软Azure OpenAI服务，需替换资源和部署名称。',
        'star': False,
    },
    {
        'id': 'deepseek',
        'name': '🔍 DeepSeek',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.deepseek.com/v1',
        'default_model': 'deepseek-v4-flash',
        'models': ['deepseek-chat', 'deepseek-coder'],
        'icon': '🔍',
        'color': '#2563eb',
        'notes': '深度求索官方接口，支持deepseek-v4-flash/deepseek-v4-pro，原生支持推理和工具调用。',
        'star': False,
    },
    {
        'id': 'zhipu',
        'name': '🔷 Zhipu GLM',
        'protocol': 'openai_compatible',
        'base_url': 'https://open.bigmodel.cn/api/paas/v4',
        'default_model': 'glm-5.2',
        'models': ['glm-5.4', 'glm-5.2', 'glm-5-flash'],
        'icon': '🔷',
        'color': '#6366f1',
        'notes': '智谱AI官方接口，GLM-5系列最新模型，用户确认5.2/5.4可用',
        'star': False,
    },
    {
        'id': 'zhipu_en',
        'name': '🔷 Zhipu GLM en',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.z.ai/v1',
        'default_model': 'glm-5',
        'models': ['glm-4-air'],
        'icon': '🔷',
        'color': '#6366f1',
        'notes': '智谱GLM英文模型系列。',
        'star': False,
    },
    {
        'id': 'qianfan',
        'name': '🐾 百度千帆',
        'protocol': 'openai_compatible',
        'base_url': 'https://qianfan.cloud.baidu.com/v2',
        'default_model': 'ernie-4.5-8k',
        'models': ['ernie-3.5-8k'],
        'icon': '🐾',
        'color': '#165dff',
        'notes': '百度智能云千帆大模型平台兼容接口。',
        'star': False,
    },
    {
        'id': 'bailian',
        'name': '🟣 Bailian',
        'protocol': 'openai_compatible',
        'base_url': 'https://bailian.aliyuncs.com/v1',
        'default_model': 'qwen-max',
        'models': ['qwen-max'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': '阿里云百炼平台兼容接口。',
        'star': False,
    },
    {
        'id': 'kimi',
        'name': '🟣 Kimi Moonshot',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.moonshot.cn/v1',
        'default_model': 'kimi-k2.6',
        'models': ['moonshot-v1-8k', 'moonshot-v1-128k'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': 'Moonshot AI官方接口，支持超长上下文。',
        'star': False,
    },
    {
        'id': 'kimi_coding',
        'name': '🟣 Kimi For Coding',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.kimi.com/v1',
        'default_model': 'kimi-for-coding',
        'models': ['moonshot-coder-v1'],
        'icon': '🟣',
        'color': '#a855f7',
        'notes': 'Kimi代码专用模型。',
        'star': False,
    },
    {
        'id': 'stepfun',
        'name': '🔹 StepFun',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.stepfun.com/v1',
        'default_model': 'step-1-32k',
        'models': ['step-1-32k', 'step-1-256k', 'step-1v-32k', 'step-2-16k', 'step-2-mini'],
        'icon': '🔹',
        'color': '#3b82f6',
        'notes': '官方接口地址正确，请填写你已开通权限的模型ID',
        'star': False,
    },
    {
        'id': 'stepfun_en',
        'name': '🔹 StepFun en',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.stepfun.ai/v1',
        'default_model': 'step-3.5-flash',
        'models': ['step-1-32k'],
        'icon': '🔹',
        'color': '#3b82f6',
        'notes': '阶跃星辰英文模型系列。',
        'star': False,
    },
    {
        'id': 'modelscope',
        'name': '🔵 ModelScope',
        'protocol': 'openai_compatible',
        'base_url': 'https://api-inference.modelscope.cn/v1',
        'default_model': 'modelscope-v1',
        'models': ['modelscope-v1'],
        'icon': '🔵',
        'color': '#3b82f6',
        'notes': '阿里达摩院ModelScope平台接口。',
        'star': False,
    },
    {
        'id': 'longcat',
        'name': '🟢 Longcat',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.longcat.chat/v1',
        'default_model': 'longcat-7b',
        'models': ['longcat-7b'],
        'icon': '🟢',
        'color': '#22c55e',
        'notes': 'Longcat长上下文模型。',
        'star': False,
    },
    {
        'id': 'minimax',
        'name': '🎙️ MiniMax',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.minimaxi.com/v1',
        'default_model': 'MiniMax-Text-01',
        'models': ['MiniMax-Text-01', 'MiniMax-M2.5', 'MiniMax-M2.7', 'MiniMax-ABAB6.5s'],
        'icon': '🎙️',
        'color': '#ec4899',
        'notes': '官方接口地址正确，请填写你已开通权限的模型ID',
        'star': False,
    },
    {
        'id': 'minimax_en',
        'name': '🎙️ MiniMax en',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.minimax.io/v1',
        'default_model': 'minimax-m2.7',
        'models': ['minimax-abab6.5'],
        'icon': '🎙️',
        'color': '#ec4899',
        'notes': 'MiniMax英文模型系列。',
        'star': False,
    },
    {
        'id': 'bailing',
        'name': '⚪ BaiLing',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.tbox.cn/v1',
        'default_model': 'bailing-v1',
        'models': ['bailing-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': '百聆大模型接口。',
        'star': False,
    },
    {
        'id': 'xiaomi_mimo',
        'name': '➖ Xiaomi MiMo',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.xiaomimimo.com/v1',
        'default_model': 'mimo-v1',
        'models': ['mimo-v1'],
        'icon': '➖',
        'color': '#6b7280',
        'notes': '小米MiMo大模型系列。',
        'star': False,
    },
    {
        'id': 'xiaomi_mimo_turbo',
        'name': '➖ Xiaomi MiMo Turbo',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.mi.ai/v1',
        'default_model': 'mimo-turbo-v1',
        'models': ['mimo-turbo-v1'],
        'icon': '➖',
        'color': '#6b7280',
        'notes': '小米MiMo Turbo系列。',
        'star': False,
    },
    {
        'id': 'novita_ai',
        'name': '▲ Novita AI',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.novita.ai/openai',
        'default_model': 'novita-v1',
        'models': ['novita-v1'],
        'icon': '▲',
        'color': '#6366f1',
        'notes': 'Novita AI大模型接口。',
        'star': False,
    },
    {
        'id': 'nvidia',
        'name': '🟢 Nvidia',
        'protocol': 'openai_compatible',
        'base_url': 'https://integrate.api.nvidia.com/v1',
        'default_model': 'nvidia-llama-3',
        'models': ['nvidia-llama-3'],
        'icon': '🟢',
        'color': '#22c55e',
        'notes': 'Nvidia NIM模型接口。',
        'star': False,
    },
    {
        'id': 'aihubmix',
        'name': '⚪ AiHubMix',
        'protocol': 'openai_compatible',
        'base_url': 'https://aihubmix.com/v1',
        'default_model': 'aihubmix-v1',
        'models': ['aihubmix-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': 'AiHubMix聚合模型接口。',
        'star': False,
    },
    {
        'id': 'cherryin',
        'name': '🔴 CherryIN',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.cherryin.com/v1',
        'default_model': 'cherry-v1',
        'models': ['cherry-v1'],
        'icon': '🔴',
        'color': '#ef4444',
        'notes': 'CherryIN模型接口。',
        'star': False,
    },
    {
        'id': 'eflowcode',
        'name': '⚪ E-FlowCode',
        'protocol': 'openai_compatible',
        'base_url': 'https://e-flowcode.cc/v1',
        'default_model': 'eflow-coder-v1',
        'models': ['eflow-coder-v1'],
        'icon': '⚪',
        'color': '#9ca3af',
        'notes': 'E-FlowCode代码模型接口。',
        'star': False,
    },
    {
        'id': 'pipellm',
        'name': '⬛ PIPELLM',
        'protocol': 'openai_compatible',
        'base_url': 'https://cc-api.pipellm.ai/v1',
        'default_model': 'pipe-v1',
        'models': ['pipe-v1'],
        'icon': '⬛',
        'color': '#18181b',
        'notes': 'PIPELLM流水线大模型接口。',
        'star': False,
    },
    {
        'id': 'openrouter',
        'name': '🔄 OpenRouter',
        'protocol': 'openai_compatible',
        'base_url': 'https://openrouter.ai/api/v1',
        'default_model': 'anthropic/claude-3-opus',
        'models': ['anthropic/claude-3-opus'],
        'icon': '🔄',
        'color': '#6366f1',
        'notes': 'OpenRouter聚合平台，支持全球数百种模型。',
        'star': False,
    },
    {
        'id': 'therouter',
        'name': '🔄 TheRouter',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.therouter.ai/v1',
        'default_model': 'router-v1',
        'models': ['router-v1'],
        'icon': '🔄',
        'color': '#6366f1',
        'notes': 'TheRouter大模型路由接口。',
        'star': False,
    },
    {
        'id': 'ollama',
        'name': '🐳 Ollama OpenAI 兼容',
        'protocol': 'openai_compatible',
        'base_url': 'http://localhost:11434/v1',
        'default_model': 'llama3.2',
        'models': ['llama3.2', 'qwen'],
        'icon': '🐳',
        'color': '#22c55e',
        'notes': '本地模型，通常不需要 API Key，可填任意占位值。',
        'star': False,
    },
    {
        'id': 'xai',
        'name': '✖️ xAI Grok',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.x.ai/v1',
        'default_model': 'grok-4',
        'models': ['grok-4', 'grok-3', 'grok-3-mini', 'grok-code-fast-1'],
        'icon': '✖️',
        'color': '#000000',
        'notes': 'xAI 官方 OpenAI 兼容端点，支持 Grok 系列。',
        'star': False,
    },
    {
        'id': 'groq',
        'name': '⚡ Groq',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.groq.com/openai/v1',
        'default_model': 'llama-3.3-70b-versatile',
        'models': ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'whisper-large-v3'],
        'icon': '⚡',
        'color': '#F55036',
        'notes': 'Groq 超快推理，OpenAI 兼容协议。',
        'star': False,
    },
    {
        'id': 'mistral',
        'name': '🟠 Mistral',
        'protocol': 'openai_compatible',
        'base_url': 'https://api.mistral.ai/v1',
        'default_model': 'mistral-large-latest',
        'models': ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest'],
        'icon': '🟠',
        'color': '#FF7000',
        'notes': 'Mistral 官方 OpenAI 兼容端点。',
        'star': False,
    },
    {
        'id': 'google',
        'name': '🔵 Google Gemini (OpenAI 兼容)',
        'protocol': 'openai_compatible',
        'base_url': 'https://generativelanguage.googleapis.com/v1beta/openai',
        'default_model': 'gemini-2.5-pro',
        'models': ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-2.0-flash-lite'],
        'icon': '🔵',
        'color': '#4285F4',
        'notes': 'Google Gemini 官方 OpenAI 兼容端点（v1beta/openai）。',
        'star': False,
    },
]
